(* File generated from arch.idl *)

type bfd_architecture =
  | Bfd_arch_unknown
  | Bfd_arch_obscure
  | Bfd_arch_m68k
  | Bfd_arch_vax
  | Bfd_arch_i960
  | Bfd_arch_or32
  | Bfd_arch_sparc
  | Bfd_arch_spu
  | Bfd_arch_mips
  | Bfd_arch_i386
  | Bfd_arch_l1om
  | Bfd_arch_we32k
  | Bfd_arch_tahoe
  | Bfd_arch_i860
  | Bfd_arch_i370
  | Bfd_arch_romp
  | Bfd_arch_convex
  | Bfd_arch_m88k
  | Bfd_arch_m98k
  | Bfd_arch_pyramid
  | Bfd_arch_h8300
  | Bfd_arch_pdp11
  | Bfd_arch_plugin
  | Bfd_arch_powerpc
  | Bfd_arch_rs6000
  | Bfd_arch_hppa
  | Bfd_arch_d10v
  | Bfd_arch_d30v
  | Bfd_arch_dlx
  | Bfd_arch_m68hc11
  | Bfd_arch_m68hc12
  | Bfd_arch_z8k
  | Bfd_arch_h8500
  | Bfd_arch_sh
  | Bfd_arch_alpha
  | Bfd_arch_arm
  | Bfd_arch_ns32k
  | Bfd_arch_w65
  | Bfd_arch_tic30
  | Bfd_arch_tic4x
  | Bfd_arch_tic54x
  | Bfd_arch_tic6x
  | Bfd_arch_tic80
  | Bfd_arch_v850
  | Bfd_arch_arc
  | Bfd_arch_m32c
  | Bfd_arch_m32r
  | Bfd_arch_mn10200
  | Bfd_arch_mn10300
  | Bfd_arch_fr30
  | Bfd_arch_frv
  | Bfd_arch_moxie
  | Bfd_arch_mcore
  | Bfd_arch_mep
  | Bfd_arch_ia64
  | Bfd_arch_ip2k
  | Bfd_arch_iq2000
  | Bfd_arch_mt
  | Bfd_arch_pj
  | Bfd_arch_avr
  | Bfd_arch_bfin
  | Bfd_arch_cr16
  | Bfd_arch_cr16c
  | Bfd_arch_crx
  | Bfd_arch_cris
  | Bfd_arch_rx
  | Bfd_arch_s390
  | Bfd_arch_score
  | Bfd_arch_openrisc
  | Bfd_arch_mmix
  | Bfd_arch_xstormy16
  | Bfd_arch_msp430
  | Bfd_arch_xc16x
  | Bfd_arch_xtensa
  | Bfd_arch_z80
  | Bfd_arch_lm32
  | Bfd_arch_microblaze
  | Bfd_arch_last

